### ISSUE TITLE
SetCount to 0 and checkZero not removing red dot

### ISSUE THREAD

**Issue by JakeEllis** [jogendra/BadgeHub#15]
When setting my count to 0 the red dot stays as 1 and does not disappear.

I have tried to call checkZero( ), decrement the count from one to zero instead of set to zero, and even refresh the views but nothing has worked.

Is there a way to remove the hub from the view it is attached to? I looked around for removing subviews from views but I could not find anything.

[badgehub screen shot.pdf](https://github.com/jogendra/BadgeHub/files/4880940/badgehub.screen.shot.pdf)

**Comment by alien142** [comment]
I think you should add this line before call checkZero() for hide badge:
hub.count = 0
